### ISSUE TITLE
Unhandled Exception: callManagerInfo

### ISSUE THREAD

**Issue by maximnikonov** [jlattimer/CRM-String-Workflow-Utilities#8]
Hi, 
Getting this error when try to execute `Gap String Functions (6.1.0.4):Gap.StringFunctions.StringReplace`
it happens inconsistently and usually success after I try to run a WF for a second time.
The full message:

`Sync workflow failed with error message - Unhandled Exception: Microsoft.Crm.Workflow.Services.InvalidCustomActivityExecutionException: callManagerInfo
   at System.Activities.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs, TimeSpan timeout, WorkflowInstanceExtensionManager extensions)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.ExecuteWorkflowUsingInvoker(Activity workflow, ICommonWorkflowContext context)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.StartWorkflow(WorkflowActivationData activationData, ICommonWorkflowContext context)
, error code - -2147220891
`

will appreciate the help.
Thanks!

**Comment by maximnikonov** [comment]
my bad, it's another project
